### PR TITLE
[BUG] Fixed bug with incorrect countdown

### LINKED ISSUE #317: [BUG] Game Countdown is incorrect
#### Describe the bug:
At the moment, certain results will go through to the countdown even if no Restaurants are returned

### To Reproduce the bug:
A clear description of the steps to reproduce the behaviour:

1. Create a lobby
2. Enter 'ASB Showgrounds Green Lane West, Epsom, Auckland, New Zealand' as the location
3. Leave every other parameter as default - the distance must be less than 5km
4. Click the "Go" button
5. Observe entering the countdown

The countdown should not be entered as no Restaurants are returned. This is observed when the distance is set to higher than 5km, it will not enter the countdown

### What it is doing:
image

### Additional context:
ZERO_RESULTS should be checked to ensure that the game does not enter the countdown screen. for some reason, the distance affects whether the ZERO_RESULTS.

### PR DESCRIPTION
**Pull request by UltimaKuma**
Fixes #317 

Was due to an incorrectly implemented for loop in the backend game loop that skipped over the final iteration. This resulted in games ending prematurely, and games with 1 restaurant causing errors for the frontend due to immediately ending.

### CODE REVIEW

File: backend/src/domain/models/Game.js [hunk 1]
```diff
@@ -55,20 +55,13 @@ export class Game {
...
    */
   async nextRound() {
-    this.round++;
-    if (this.round === this.swipeDeck.length) {
-      this.endGame();
-      return;
-    }
-
-
-    for (let i=1; i < this.swipeDeck.length; i++) {
```
Comment (UltimaKuma) [inline backend/src/domain/models/Game.js:65]: If there was only 1 restaurant, would have skipped the for loop and immediately ended the game

File: backend/src/domain/models/Game.js [hunk 2]
```diff
@@ -55,20 +55,13 @@ export class Game {
    * of the session
    */
   async nextRound() {
-    this.round++;
```
Comment (UltimaKuma) [inline backend/src/domain/models/Game.js:58]: Redundant code as this function is only called once. Thus round will always be at 1.

**Comment by reeved** [comment]
Hey Leon,

I was testing your PR with the following params: 
"Grafton, Auckland, New Zealand", with everything else default (it used to return just one restaurant to swipe)

But the restaurant repeats twice before the game ends. The params mentioned in #317 work fine though.

Could you please try this out on your environment and let me know what you find?

**Review by reeved — APPROVED** [review]
wooooooooooooooo thanks for fixing this bug!!!

Have tested it out decently and everything seems to function as expected.

Great work Leon!

**Review by MKTPR — APPROVED** [review]
I've cloned the branch and tested it locally to check that it works. The code looks great as well, only involving small changes from the original code! Great catch on those details and nice job.
